# Pandas
### A fast, powerful, flexible and easy to use open source data analysis and manipulation python library

## Installation of Pandas

$ conda install pandas

## Getting started with Pandas

In [1]:
import pandas as pd

### Reading CSV files with Pandas

In [2]:
df = pd.read_csv("employees.csv")
df

,Emp ID,Name Prefix,First Name,Middle Initial,Last Name,Gender,E Mail,Father's Name,Mother's Name,Mother's Maiden Name,...,SSN,Phone No.,Place Name,County,City,State,Zip,Region,User Name,Password
0,526540,Ms.,Angelique,K,Goodwin,F,angelique.goodwin@gmail.com,Rick Goodwin,Dorian Goodwin,Maxey,...,471-57-0359,212-884-7146,Rochester,Monroe,Rochester,NY,14624,Northeast,akgoodwin,z{d>ez%{.@
1,859327,Ms.,Jeni,S,Shaffer,F,jeni.shaffer@gmail.com,Ryan Shaffer,Love Shaffer,Gunderson,...,624-85-4146,205-665-7020,Luverne,Crenshaw,Luverne,AL,36049,South,jsshaffer,7U56!*!O
2,887387,Ms.,Donald,T,Farris,F,donald.farris@bellsouth.net,Mauro Farris,Edyth Farris,Greer,...,097-02-3315,205-959-7879,Hodges,Franklin,Hodges,AL,35571,South,dtfarris,rX.F{j&]&m&&X
3,779497,Hon.,Steven,D,Rendon,M,steven.rendon@gmail.com,Elden Rendon,Angela Rendon,Ortiz,...,134-98-6566,217-858-0054,Savoy,Champaign,Savoy,IL,61874,Midwest,sdrendon,a+2;sx}<G]y
4,896517,Drs.,Jenell,L,Almanza,F,jenell.almanza@yahoo.com,Clifford Almanza,Vergie Almanza,Darby,...,599-92-7345,314-893-2590,Stet,Carroll,Stet,MO,64680,Midwest,jlalmanza,Ou7RX{yT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,488800,Mr.,Roberto,R,Harter,M,roberto.harter@exxonmobil.com,Murray Harter,Merideth Harter,Musgrove,...,222-11-0199,212-999-7351,New York City,New York,New York City,NY,10185,Northeast,rrharter,b>|V#Ywx
4996,428330,Hon.,Brittni,B,Cyr,F,brittni.cyr@earthlink.net,Williams Cyr,Darleen Cyr,Henderson,...,501-37-5977,252-912-0511,Willow Spring,Wake,Willow Spring,NC,27592,South,bbcyr,We/b$tUwvstNmE2
4997,313027,Mr.,Gerald,J,Beaudry,M,gerald.beaudry@shaw.ca,Zachary Beaudry,Sadie Beaudry,Labelle,...,199-84-4215,219-983-1836,Burney,Burney,Burney,IN,47222,Midwest,gjbeaudry,hAw[]_s-
4998,826852,Mrs.,Emilee,D,Emery,F,emilee.emery@gmail.com,Andres Emery,Lavina Emery,Metzler,...,720-18-9456,262-661-9794,Madison,Dane,Madison,WI,53706,Midwest,edemery,jj0uKCopdM
4999,948300,Ms.,Larhonda,G,Dozier,F,larhonda.dozier@aol.com,Houston Dozier,Gene Dozier,Richard,...,491-29-1497,206-229-2748,Spokane,Spokane,Spokane,WA,99224,West,lgdozier,we_Uppg02

### Pandas has two main data structures:

1. **DataFrames** - 2 dimensional data structure, equivalent to a table of data
2. **Series** - 1 dimensional data structure, for example a column of data or a row of data

### Understanding the data

In [3]:
df.shape

(5000, 37)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 37 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Emp ID                  5000 non-null   int64
 1   Name Prefix             5000 non-null   object
 2   First Name              5000 non-null   object
 3   Middle Initial          5000 non-null   object
 4   Last Name               5000 non-null   object
 5   Gender                  5000 non-null   object
 6   E Mail                  5000 non-null   object
 7   Father's Name           5000 non-null   object
 8   Mother's Name           5000 non-null   object
 9   Mother's Maiden Name    5000 non-null   object
 10  Date of Birth           5000 non-null   object
 11  Time of Birth           5000 non-null   object
 12  Age in Yrs.             5000 non-null   float64
 13  Weight in Kgs.          5000 non-null   int64
 14  Date of Joining         5000 non-null   object
 15  Quarter of Joining      5000 non-null   object
 16  Half of Joining         5000 non-null   object
 17  Year of Joining         5000 non-null   int64
 18  Month of Joining        5000 non-null   int64
 19  Month Name of Joining   5000 non-null   object
 20  Short Month             5000 non-null   object
 21  Day of Joining          5000 non-null   int64
 22  DOW of Joining          5000 non-null   object
 23  Short DOW               5000 non-null   object
 24  Age in Company (Years)  5000 non-null   float64
 25  Salary                  5000 non-null   int64
 26  Last % Hike             5000 non-null   object
 27  SSN                     5000 non-null   object
 28  Phone No.               5000 non-null   object
 29  Place Name              5000 non-null   object
 30  County                  5000 non-null   object
 31  City                    5000 non-null   object
 32  State                   5000 non-null   object
 33  Zip                     5000 non-null   int64
 34  Region                  5000 non-null   object
 35  User Name               5000 non-null   object
 36  Password                5000 non-null   object
dtypes: float64(2), int64(7), object(28)
memory usage: 1.4+ MB

In [5]:
df.columns

Index(['Emp ID', 'Name Prefix', 'First Name', 'Middle Initial', 'Last Name',
       'Gender', 'E Mail', 'Father's Name', 'Mother's Name',
       'Mother's Maiden Name', 'Date of Birth', 'Time of Birth', 'Age in Yrs.',
       'Weight in Kgs.', 'Date of Joining', 'Quarter of Joining',
       'Half of Joining', 'Year of Joining', 'Month of Joining',
       'Month Name of Joining', 'Short Month', 'Day of Joining',
       'DOW of Joining', 'Short DOW', 'Age in Company (Years)', 'Salary',
       'Last % Hike', 'SSN', 'Phone No. ', 'Place Name', 'County', 'City',
       'State', 'Zip', 'Region', 'User Name', 'Password'],
      dtype='object')

### Looking through the data

In [7]:
df.head(8)

,Emp ID,Name Prefix,First Name,Middle Initial,Last Name,Gender,E Mail,Father's Name,Mother's Name,Mother's Maiden Name,...,SSN,Phone No.,Place Name,County,City,State,Zip,Region,User Name,Password
0,526540,Ms.,Angelique,K,Goodwin,F,angelique.goodwin@gmail.com,Rick Goodwin,Dorian Goodwin,Maxey,...,471-57-0359,212-884-7146,Rochester,Monroe,Rochester,NY,14624,Northeast,akgoodwin,z{d>ez%{.@
1,859327,Ms.,Jeni,S,Shaffer,F,jeni.shaffer@gmail.com,Ryan Shaffer,Love Shaffer,Gunderson,...,624-85-4146,205-665-7020,Luverne,Crenshaw,Luverne,AL,36049,South,jsshaffer,7U56!*!O
2,887387,Ms.,Donald,T,Farris,F,donald.farris@bellsouth.net,Mauro Farris,Edyth Farris,Greer,...,097-02-3315,205-959-7879,Hodges,Franklin,Hodges,AL,35571,South,dtfarris,rX.F{j&]&m&&X
3,779497,Hon.,Steven,D,Rendon,M,steven.rendon@gmail.com,Elden Rendon,Angela Rendon,Ortiz,...,134-98-6566,217-858-0054,Savoy,Champaign,Savoy,IL,61874,Midwest,sdrendon,a+2;sx}<G]y
4,896517,Drs.,Jenell,L,Almanza,F,jenell.almanza@yahoo.com,Clifford Almanza,Vergie Almanza,Darby,...,599-92-7345,314-893-2590,Stet,Carroll,Stet,MO,64680,Midwest,jlalmanza,Ou7RX{yT
5,220965,Mrs.,Almeta,Y,Brookins,F,almeta.brookins@gmail.com,Richard Brookins,Angelika Brookins,Pape,...,109-98-3095,229-238-0915,Lyons,Toombs,Lyons,GA,30436,South,aybrookins,HQHKE_+9hv
6,721091,Prof.,Bobbie,E,Branson,M,bobbie.branson@hotmail.com,Joan Branson,Nu Branson,Frazer,...,047-15-8435,216-849-6986,Kalida,Putnam,Kalida,OH,45853,Midwest,bebranson,tA5zrwtY9\!Y
7,633636,Prof.,Bertram,R,Carlisle,M,bertram.carlisle@aol.com,Ivory Carlisle,Bao Carlisle,Cintron,...,257-99-3865,215-614-1953,Hamilton,Jefferson,Hamilton,PA,15744,Northeast,brcarlisle,F4G46Phi$qF

In [8]:
df.tail(4)

,Emp ID,Name Prefix,First Name,Middle Initial,Last Name,Gender,E Mail,Father's Name,Mother's Name,Mother's Maiden Name,...,SSN,Phone No.,Place Name,County,City,State,Zip,Region,User Name,Password
4996,428330,Hon.,Brittni,B,Cyr,F,brittni.cyr@earthlink.net,Williams Cyr,Darleen Cyr,Henderson,...,501-37-5977,252-912-0511,Willow Spring,Wake,Willow Spring,NC,27592,South,bbcyr,We/b$tUwvstNmE2
4997,313027,Mr.,Gerald,J,Beaudry,M,gerald.beaudry@shaw.ca,Zachary Beaudry,Sadie Beaudry,Labelle,...,199-84-4215,219-983-1836,Burney,Burney,Burney,IN,47222,Midwest,gjbeaudry,hAw[]_s-
4998,826852,Mrs.,Emilee,D,Emery,F,emilee.emery@gmail.com,Andres Emery,Lavina Emery,Metzler,...,720-18-9456,262-661-9794,Madison,Dane,Madison,WI,53706,Midwest,edemery,jj0uKCopdM
4999,948300,Ms.,Larhonda,G,Dozier,F,larhonda.dozier@aol.com,Houston Dozier,Gene Dozier,Richard,...,491-29-1497,206-229-2748,Spokane,Spokane,Spokane,WA,99224,West,lgdozier,we_Uppg02

### Retrieving a column of data

In [15]:
df.Gender

0       F
1       F
2       F
3       M
4       F
       ..
4995    M
4996    F
4997    M
4998    F
4999    F
Name: Gender, Length: 5000, dtype: object

In [17]:
df[["E Mail", "Gender"]]

                             E Mail Gender
0       angelique.goodwin@gmail.com      F
1            jeni.shaffer@gmail.com      F
2       donald.farris@bellsouth.net      F
3           steven.rendon@gmail.com      M
4          jenell.almanza@yahoo.com      F
...                             ...    ...
4995  roberto.harter@exxonmobil.com      M
4996      brittni.cyr@earthlink.net      F
4997         gerald.beaudry@shaw.ca      M
4998         emilee.emery@gmail.com      F
4999        larhonda.dozier@aol.com      F

[5000 rows x 2 columns]

### Accessing specific rows

In [20]:
df.iloc[4]

Emp ID                                      896517
Name Prefix                                   Drs.
First Name                                  Jenell
Middle Initial                                   L
Last Name                                  Almanza
Gender                                           F
E Mail                    jenell.almanza@yahoo.com
Father's Name                     Clifford Almanza
Mother's Name                       Vergie Almanza
Mother's Maiden Name                         Darby
Date of Birth                             7/1/1958
Time of Birth                          04:28:54 AM
Age in Yrs.                                  59.12
Weight in Kgs.                                  47
Date of Joining                          7/14/1993
Quarter of Joining                              Q3
Half of Joining                                 H2
Year of Joining                               1993
Month of Joining                                 7
Month Name of Joining                         July
Short Month                                    Jul
Day of Joining                                  14
DOW of Joining                           Wednesday
Short DOW                                      Wed
Age in Company (Years)                       24.05
Salary                                      139856
Last % Hike                                     6%
SSN                                    599-92-7345
Phone No.                             314-893-2590
Place Name                                    Stet
County                                     Carroll
City                                          Stet
State                                           MO
Zip                                          64680
Region                                     Midwest
User Name                                jlalmanza
Password                                  Ou7RX{yT
Name: 4, dtype: object

In [21]:
df.iloc[[4, 9]]

,Emp ID,Name Prefix,First Name,Middle Initial,Last Name,Gender,E Mail,Father's Name,Mother's Name,Mother's Maiden Name,...,SSN,Phone No.,Place Name,County,City,State,Zip,Region,User Name,Password
4,896517,Drs.,Jenell,L,Almanza,F,jenell.almanza@yahoo.com,Clifford Almanza,Vergie Almanza,Darby,...,599-92-7345,314-893-2590,Stet,Carroll,Stet,MO,64680,Midwest,jlalmanza,Ou7RX{yT
9,413865,Mr.,Todd,R,Slater,M,todd.slater@earthlink.net,Donnie Slater,Shay Slater,Conaway,...,553-99-2106,218-671-2547,Young America,Carver,Young America,MN,55558,Midwest,trslater,EZ5}EHI4

In [25]:
df.iloc[10:21, [2, 4]]

   First Name   Last Name
10  Adalberto       Hazel
11    Seymour      Nelson
12    Vicente     Dawkins
13        Rex          Ng
14     Arlena      Clough
15       Cory      Clarke
16      Sofia       Poole
17     Samuel       Wendt
18     Virgil  Trowbridge
19       Elda   Champagne
20     Robert       Guinn

### We need to talk about indexes

In [26]:
df

,Emp ID,Name Prefix,First Name,Middle Initial,Last Name,Gender,E Mail,Father's Name,Mother's Name,Mother's Maiden Name,...,SSN,Phone No.,Place Name,County,City,State,Zip,Region,User Name,Password
0,526540,Ms.,Angelique,K,Goodwin,F,angelique.goodwin@gmail.com,Rick Goodwin,Dorian Goodwin,Maxey,...,471-57-0359,212-884-7146,Rochester,Monroe,Rochester,NY,14624,Northeast,akgoodwin,z{d>ez%{.@
1,859327,Ms.,Jeni,S,Shaffer,F,jeni.shaffer@gmail.com,Ryan Shaffer,Love Shaffer,Gunderson,...,624-85-4146,205-665-7020,Luverne,Crenshaw,Luverne,AL,36049,South,jsshaffer,7U56!*!O
2,887387,Ms.,Donald,T,Farris,F,donald.farris@bellsouth.net,Mauro Farris,Edyth Farris,Greer,...,097-02-3315,205-959-7879,Hodges,Franklin,Hodges,AL,35571,South,dtfarris,rX.F{j&]&m&&X
3,779497,Hon.,Steven,D,Rendon,M,steven.rendon@gmail.com,Elden Rendon,Angela Rendon,Ortiz,...,134-98-6566,217-858-0054,Savoy,Champaign,Savoy,IL,61874,Midwest,sdrendon,a+2;sx}<G]y
4,896517,Drs.,Jenell,L,Almanza,F,jenell.almanza@yahoo.com,Clifford Almanza,Vergie Almanza,Darby,...,599-92-7345,314-893-2590,Stet,Carroll,Stet,MO,64680,Midwest,jlalmanza,Ou7RX{yT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,488800,Mr.,Roberto,R,Harter,M,roberto.harter@exxonmobil.com,Murray Harter,Merideth Harter,Musgrove,...,222-11-0199,212-999-7351,New York City,New York,New York City,NY,10185,Northeast,rrharter,b>|V#Ywx
4996,428330,Hon.,Brittni,B,Cyr,F,brittni.cyr@earthlink.net,Williams Cyr,Darleen Cyr,Henderson,...,501-37-5977,252-912-0511,Willow Spring,Wake,Willow Spring,NC,27592,South,bbcyr,We/b$tUwvstNmE2
4997,313027,Mr.,Gerald,J,Beaudry,M,gerald.beaudry@shaw.ca,Zachary Beaudry,Sadie Beaudry,Labelle,...,199-84-4215,219-983-1836,Burney,Burney,Burney,IN,47222,Midwest,gjbeaudry,hAw[]_s-
4998,826852,Mrs.,Emilee,D,Emery,F,emilee.emery@gmail.com,Andres Emery,Lavina Emery,Metzler,...,720-18-9456,262-661-9794,Madison,Dane,Madison,WI,53706,Midwest,edemery,jj0uKCopdM
4999,948300,Ms.,Larhonda,G,Dozier,F,larhonda.dozier@aol.com,Houston Dozier,Gene Dozier,Richard,...,491-29-1497,206-229-2748,Spokane,Spokane,Spokane,WA,99224,West,lgdozier,we_Uppg02

In [34]:
#df.set_index("Emp ID")
df

,Name Prefix,First Name,Middle Initial,Last Name,Gender,E Mail,Father's Name,Mother's Name,Mother's Maiden Name,Date of Birth,...,SSN,Phone No.,Place Name,County,City,State,Zip,Region,User Name,Password
Emp ID,,,,,,,,,,,,,,,,,,,,,
526540,Ms.,Angelique,K,Goodwin,F,angelique.goodwin@gmail.com,Rick Goodwin,Dorian Goodwin,Maxey,5/15/1964,...,471-57-0359,212-884-7146,Rochester,Monroe,Rochester,NY,14624,Northeast,akgoodwin,z{d>ez%{.@
859327,Ms.,Jeni,S,Shaffer,F,jeni.shaffer@gmail.com,Ryan Shaffer,Love Shaffer,Gunderson,1/13/1962,...,624-85-4146,205-665-7020,Luverne,Crenshaw,Luverne,AL,36049,South,jsshaffer,7U56!*!O
887387,Ms.,Donald,T,Farris,F,donald.farris@bellsouth.net,Mauro Farris,Edyth Farris,Greer,4/11/1958,...,097-02-3315,205-959-7879,Hodges,Franklin,Hodges,AL,35571,South,dtfarris,rX.F{j&]&m&&X
779497,Hon.,Steven,D,Rendon,M,steven.rendon@gmail.com,Elden Rendon,Angela Rendon,Ortiz,4/4/1982,...,134-98-6566,217-858-0054,Savoy,Champaign,Savoy,IL,61874,Midwest,sdrendon,a+2;sx}<G]y
896517,Drs.,Jenell,L,Almanza,F,jenell.almanza@yahoo.com,Clifford Almanza,Vergie Almanza,Darby,7/1/1958,...,599-92-7345,314-893-2590,Stet,Carroll,Stet,MO,64680,Midwest,jlalmanza,Ou7RX{yT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488800,Mr.,Roberto,R,Harter,M,roberto.harter@exxonmobil.com,Murray Harter,Merideth Harter,Musgrove,7/9/1994,...,222-11-0199,212-999-7351,New York City,New York,New York City,NY,10185,Northeast,rrharter,b>|V#Ywx
428330,Hon.,Brittni,B,Cyr,F,brittni.cyr@earthlink.net,Williams Cyr,Darleen Cyr,Henderson,3/16/1970,...,501-37-5977,252-912-0511,Willow Spring,Wake,Willow Spring,NC,27592,South,bbcyr,We/b$tUwvstNmE2
313027,Mr.,Gerald,J,Beaudry,M,gerald.beaudry@shaw.ca,Zachary Beaudry,Sadie Beaudry,Labelle,4/21/1982,...,199-84-4215,219-983-1836,Burney,Burney,Burney,IN,47222,Midwest,gjbeaudry,hAw[]_s-
826852,Mrs.,Emilee,D,Emery,F,emilee.emery@gmail.com,Andres Emery,Lavina Emery,Metzler,6/18/1967,...,720-18-9456,262-661-9794,Madison,Dane,Madison,WI,53706,Midwest,edemery,jj0uKCopdM
948300,Ms.,Larhonda,G,Dozier,F,larhonda.dozier@aol.com,Houston Dozier,Gene Dozier,Richard,1/8/1987,...,491-29-1497,206-229-2748,Spokane,Spokane,Spokane,WA,99224,West,lgdozier,we_Uppg02

In [36]:
df.sort_index(ascending=False)

,Name Prefix,First Name,Middle Initial,Last Name,Gender,E Mail,Father's Name,Mother's Name,Mother's Maiden Name,Date of Birth,...,SSN,Phone No.,Place Name,County,City,State,Zip,Region,User Name,Password
Emp ID,,,,,,,,,,,,,,,,,,,,,
999800,Mrs.,Yolando,W,Stillwell,F,yolando.stillwell@hotmail.com,Eldridge Stillwell,Lona Stillwell,Surratt,3/10/1981,...,652-62-0572,304-364-2062,Flat Top,Mercer,Flat Top,WV,25841,South,ywstillwell,ht3-VRL-5|%{
999496,Mr.,Bryan,X,Burks,M,bryan.burks@gmail.com,Antone Burks,Ossie Burks,Paulk,1/5/1976,...,609-87-1719,252-432-9184,Charlotte,Mecklenburg,Charlotte,NC,28262,South,bxburks,8D9jX1-9R+^
999422,Hon.,Lorrie,V,Baber,F,lorrie.baber@gmail.com,Carmine Baber,Temeka Baber,Pack,11/20/1995,...,091-02-5727,212-273-3932,Blossvale,Oneida,Blossvale,NY,13308,Northeast,lvbaber,r1C\~kk]Uu
999307,Mr.,Daryl,C,Treadwell,M,daryl.treadwell@verizon.net,Moshe Treadwell,Phyllis Treadwell,Schwarz,7/7/1977,...,211-84-3295,225-622-2835,Torbert,Pointe Coupee,Torbert,LA,70781,South,dctreadwell,8Wq?HZS[MhF
998903,Mrs.,Chasity,H,Guido,F,chasity.guido@charter.net,Thomas Guido,Florance Guido,Landers,7/2/1986,...,673-48-9419,316-201-0028,Protection,Comanche,Protection,KS,67127,Midwest,chguido,b*4&3d8Aouc:D9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112680,Mr.,Ira,V,Nathan,M,ira.nathan@gmail.com,Jayson Nathan,Charleen Nathan,Isbell,12/18/1967,...,055-02-8158,270-460-7860,Lancaster,Garrard,Lancaster,KY,40446,South,ivnathan,O|VC]y_3a/.
112574,Dr.,Raleigh,O,Osorio,M,raleigh.osorio@yahoo.com,Stewart Osorio,Pamelia Osorio,Stroud,4/15/1992,...,070-02-2841,209-947-7543,Mission Hills,Los Angeles,Mission Hills,CA,91395,West,roosorio,M6zTzQTaShxE
111692,Dr.,Emil,Q,Parris,M,emil.parris@yahoo.com,Keith Parris,Chantal Parris,Dasilva,7/15/1983,...,503-45-6054,209-224-4155,Desert Center,Riverside,Desert Center,CA,92239,West,eqparris,y}axOm>z
111500,Hon.,Jarrett,M,Yanez,M,jarrett.yanez@gmail.com,Brady Yanez,Dena Yanez,Packard,6/20/1981,...,750-20-6130,316-289-0524,Hepler,Crawford,Hepler,KS,66746,Midwest,jmyanez,K|^5$R1@5bO
111150,Drs.,Sanjuana,E,Saddler,F,sanjuana.saddler@gmail.com,Gerard Saddler,Laura Saddler,Marquis,5/13/1959,...,443-27-9742,319-879-4386,Des Moines,Polk,Des Moines,IA,50368,Midwest,sesaddler,9X86]CTj

In [44]:
df.loc[[526540, 896517], ["Last Name", "Gender"]]

       Last Name Gender
Emp ID
526540   Goodwin      F
896517   Almanza      F

### Filtering data

In [48]:
filt = df["Region"] == "West"
df[filt]

,Name Prefix,First Name,Middle Initial,Last Name,Gender,E Mail,Father's Name,Mother's Name,Mother's Maiden Name,Date of Birth,...,SSN,Phone No.,Place Name,County,City,State,Zip,Region,User Name,Password
Emp ID,,,,,,,,,,,,,,,,,,,,,
495667,Mr.,Cory,H,Clarke,M,cory.clarke@shell.com,Lynwood Clarke,Fallon Clarke,Velez,6/2/1980,...,731-28-8642,480-381-5936,Mesa,Maricopa,Mesa,AZ,85207,West,chclarke,k2QH6T#d!
489275,Ms.,Collene,O,Kidd,F,collene.kidd@shell.com,Rene Kidd,Lili Kidd,Knight,2/25/1965,...,704-18-2387,209-293-8759,Reedley,Fresno,Reedley,CA,93654,West,cokidd,goocZI#~7N!7suU
466560,Hon.,Dolores,A,Begley,F,dolores.begley@hotmail.com,Wilmer Begley,Jaqueline Begley,Goldman,12/16/1981,...,019-94-6803,209-877-7013,Shasta Lake,Shasta,Shasta Lake,CA,96019,West,dabegley,8e;FDv*HnOG
976422,Mr.,Jake,W,Espinal,M,jake.espinal@shaw.ca,Edmundo Espinal,Charlott Espinal,Duran,1/19/1959,...,594-99-8803,209-739-8484,Ventura,Ventura,Ventura,CA,93003,West,jwespinal,oKz3l$S2Q|sY41
713294,Mr.,Sammy,Y,Dewitt,M,sammy.dewitt@ibm.com,Issac Dewitt,Laurene Dewitt,Moniz,1/24/1988,...,729-28-6911,206-468-7536,Redondo,King,Redondo,WA,98054,West,sydewitt,Quwicz}Ebz
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
574746,Mr.,Cortez,S,Easter,M,cortez.easter@sbcglobal.net,Josh Easter,Loida Easter,Strong,11/16/1970,...,227-99-4839,209-609-4452,Biggs,Butte,Biggs,CA,95917,West,cseaster,1ZeEF?Qn+
692473,Mr.,Hugo,J,Joiner,M,hugo.joiner@ntlworld.com,Lauren Joiner,Lenora Joiner,Lindley,12/7/1972,...,290-15-1947,808-287-1509,Honolulu,Honolulu,Honolulu,HI,96824,West,hjjoiner,S7JHpbW4NA5@}{
699529,Hon.,Spencer,V,Danforth,M,spencer.danforth@gmail.com,Lawerence Danforth,Angila Danforth,Bard,1/20/1984,...,491-29-9569,208-333-3767,Plummer,Benewah,Plummer,ID,83851,West,svdanforth,D3C#BU8%k<dJBa
168076,Mr.,Romeo,Z,Goodwin,M,romeo.goodwin@gmail.com,Marcus Goodwin,Shakia Goodwin,Mcswain,6/14/1975,...,385-37-7439,303-525-0188,Broomfield,Broomfield,Broomfield,CO,80023,West,rzgoodwin,lpVkCgur~ziz
948300,Ms.,Larhonda,G,Dozier,F,larhonda.dozier@aol.com,Houston Dozier,Gene Dozier,Richard,1/8/1987,...,491-29-1497,206-229-2748,Spokane,Spokane,Spokane,WA,99224,West,lgdozier,we_Uppg02

In [52]:
filt = (df["Region"] == "West") & (df["Zip"] > 90000)

df.loc[filt, ["First Name", "Last Name"]]

       First Name Last Name
Emp ID
489275    Collene      Kidd
466560    Dolores    Begley
976422       Jake   Espinal
713294      Sammy    Dewitt
885395      Tayna    Poston
...           ...       ...
234180      Genny    Baxter
238785      Lonna  Mccarter
574746     Cortez    Easter
692473       Hugo    Joiner
948300   Larhonda    Dozier

[517 rows x 2 columns]

### Manipulating and making changes to data

### Changing column headers

In [56]:
df.rename(columns={"E Mail": "EMail Address"}, inplace=True)

In [58]:
df.columns = [x.upper() for x in df.columns]
df

,NAME_PREFIX,FIRST_NAME,MIDDLE_INITIAL,LAST_NAME,GENDER,EMAIL_ADDRESS,FATHER'S_NAME,MOTHER'S_NAME,MOTHER'S_MAIDEN_NAME,DATE_OF_BIRTH,...,SSN,PHONE_NO._,PLACE_NAME,COUNTY,CITY,STATE,ZIP,REGION,USER_NAME,PASSWORD
Emp ID,,,,,,,,,,,,,,,,,,,,,
526540,Ms.,Angelique,K,Goodwin,F,angelique.goodwin@gmail.com,Rick Goodwin,Dorian Goodwin,Maxey,5/15/1964,...,471-57-0359,212-884-7146,Rochester,Monroe,Rochester,NY,14624,Northeast,akgoodwin,z{d>ez%{.@
859327,Ms.,Jeni,S,Shaffer,F,jeni.shaffer@gmail.com,Ryan Shaffer,Love Shaffer,Gunderson,1/13/1962,...,624-85-4146,205-665-7020,Luverne,Crenshaw,Luverne,AL,36049,South,jsshaffer,7U56!*!O
887387,Ms.,Donald,T,Farris,F,donald.farris@bellsouth.net,Mauro Farris,Edyth Farris,Greer,4/11/1958,...,097-02-3315,205-959-7879,Hodges,Franklin,Hodges,AL,35571,South,dtfarris,rX.F{j&]&m&&X
779497,Hon.,Steven,D,Rendon,M,steven.rendon@gmail.com,Elden Rendon,Angela Rendon,Ortiz,4/4/1982,...,134-98-6566,217-858-0054,Savoy,Champaign,Savoy,IL,61874,Midwest,sdrendon,a+2;sx}<G]y
896517,Drs.,Jenell,L,Almanza,F,jenell.almanza@yahoo.com,Clifford Almanza,Vergie Almanza,Darby,7/1/1958,...,599-92-7345,314-893-2590,Stet,Carroll,Stet,MO,64680,Midwest,jlalmanza,Ou7RX{yT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488800,Mr.,Roberto,R,Harter,M,roberto.harter@exxonmobil.com,Murray Harter,Merideth Harter,Musgrove,7/9/1994,...,222-11-0199,212-999-7351,New York City,New York,New York City,NY,10185,Northeast,rrharter,b>|V#Ywx
428330,Hon.,Brittni,B,Cyr,F,brittni.cyr@earthlink.net,Williams Cyr,Darleen Cyr,Henderson,3/16/1970,...,501-37-5977,252-912-0511,Willow Spring,Wake,Willow Spring,NC,27592,South,bbcyr,We/b$tUwvstNmE2
313027,Mr.,Gerald,J,Beaudry,M,gerald.beaudry@shaw.ca,Zachary Beaudry,Sadie Beaudry,Labelle,4/21/1982,...,199-84-4215,219-983-1836,Burney,Burney,Burney,IN,47222,Midwest,gjbeaudry,hAw[]_s-
826852,Mrs.,Emilee,D,Emery,F,emilee.emery@gmail.com,Andres Emery,Lavina Emery,Metzler,6/18/1967,...,720-18-9456,262-661-9794,Madison,Dane,Madison,WI,53706,Midwest,edemery,jj0uKCopdM
948300,Ms.,Larhonda,G,Dozier,F,larhonda.dozier@aol.com,Houston Dozier,Gene Dozier,Richard,1/8/1987,...,491-29-1497,206-229-2748,Spokane,Spokane,Spokane,WA,99224,West,lgdozier,we_Uppg02

### Changing data

In [61]:
df["PASSWORD"] = "default"
df

,NAME_PREFIX,FIRST_NAME,MIDDLE_INITIAL,LAST_NAME,GENDER,EMAIL_ADDRESS,FATHER'S_NAME,MOTHER'S_NAME,MOTHER'S_MAIDEN_NAME,DATE_OF_BIRTH,...,SSN,PHONE_NO._,PLACE_NAME,COUNTY,CITY,STATE,ZIP,REGION,USER_NAME,PASSWORD
Emp ID,,,,,,,,,,,,,,,,,,,,,
526540,Ms.,Angelique,K,Goodwin,F,angelique.goodwin@gmail.com,Rick Goodwin,Dorian Goodwin,Maxey,5/15/1964,...,471-57-0359,212-884-7146,Rochester,Monroe,Rochester,NY,14624,Northeast,akgoodwin,default
859327,Ms.,Jeni,S,Shaffer,F,jeni.shaffer@gmail.com,Ryan Shaffer,Love Shaffer,Gunderson,1/13/1962,...,624-85-4146,205-665-7020,Luverne,Crenshaw,Luverne,AL,36049,South,jsshaffer,default
887387,Ms.,Donald,T,Farris,F,donald.farris@bellsouth.net,Mauro Farris,Edyth Farris,Greer,4/11/1958,...,097-02-3315,205-959-7879,Hodges,Franklin,Hodges,AL,35571,South,dtfarris,default
779497,Hon.,Steven,D,Rendon,M,steven.rendon@gmail.com,Elden Rendon,Angela Rendon,Ortiz,4/4/1982,...,134-98-6566,217-858-0054,Savoy,Champaign,Savoy,IL,61874,Midwest,sdrendon,default
896517,Drs.,Jenell,L,Almanza,F,jenell.almanza@yahoo.com,Clifford Almanza,Vergie Almanza,Darby,7/1/1958,...,599-92-7345,314-893-2590,Stet,Carroll,Stet,MO,64680,Midwest,jlalmanza,default
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488800,Mr.,Roberto,R,Harter,M,roberto.harter@exxonmobil.com,Murray Harter,Merideth Harter,Musgrove,7/9/1994,...,222-11-0199,212-999-7351,New York City,New York,New York City,NY,10185,Northeast,rrharter,default
428330,Hon.,Brittni,B,Cyr,F,brittni.cyr@earthlink.net,Williams Cyr,Darleen Cyr,Henderson,3/16/1970,...,501-37-5977,252-912-0511,Willow Spring,Wake,Willow Spring,NC,27592,South,bbcyr,default
313027,Mr.,Gerald,J,Beaudry,M,gerald.beaudry@shaw.ca,Zachary Beaudry,Sadie Beaudry,Labelle,4/21/1982,...,199-84-4215,219-983-1836,Burney,Burney,Burney,IN,47222,Midwest,gjbeaudry,default
826852,Mrs.,Emilee,D,Emery,F,emilee.emery@gmail.com,Andres Emery,Lavina Emery,Metzler,6/18/1967,...,720-18-9456,262-661-9794,Madison,Dane,Madison,WI,53706,Midwest,edemery,default
948300,Ms.,Larhonda,G,Dozier,F,larhonda.dozier@aol.com,Houston Dozier,Gene Dozier,Richard,1/8/1987,...,491-29-1497,206-229-2748,Spokane,Spokane,Spokane,WA,99224,West,lgdozier,default

In [65]:
filt = df["FIRST_NAME"] == "Stephen"
df.loc[filt, "LAST_NAME"] = "Hawking"

### Adding Columns

In [68]:
df["Full name"] = df["FIRST_NAME"] + " " + df["LAST_NAME"]
df

,NAME_PREFIX,FIRST_NAME,MIDDLE_INITIAL,LAST_NAME,GENDER,EMAIL_ADDRESS,FATHER'S_NAME,MOTHER'S_NAME,MOTHER'S_MAIDEN_NAME,DATE_OF_BIRTH,...,PLACE_NAME,COUNTY,CITY,STATE,ZIP,REGION,USER_NAME,PASSWORD,New col,Full name
Emp ID,,,,,,,,,,,,,,,,,,,,,
526540,Ms.,Angelique,K,Goodwin,F,angelique.goodwin@gmail.com,Rick Goodwin,Dorian Goodwin,Maxey,5/15/1964,...,Rochester,Monroe,Rochester,NY,14624,Northeast,akgoodwin,default,default value,Angelique Goodwin
859327,Ms.,Jeni,S,Shaffer,F,jeni.shaffer@gmail.com,Ryan Shaffer,Love Shaffer,Gunderson,1/13/1962,...,Luverne,Crenshaw,Luverne,AL,36049,South,jsshaffer,default,default value,Jeni Shaffer
887387,Ms.,Donald,T,Farris,F,donald.farris@bellsouth.net,Mauro Farris,Edyth Farris,Greer,4/11/1958,...,Hodges,Franklin,Hodges,AL,35571,South,dtfarris,default,default value,Donald Farris
779497,Hon.,Steven,D,Rendon,M,steven.rendon@gmail.com,Elden Rendon,Angela Rendon,Ortiz,4/4/1982,...,Savoy,Champaign,Savoy,IL,61874,Midwest,sdrendon,default,default value,Steven Rendon
896517,Drs.,Jenell,L,Almanza,F,jenell.almanza@yahoo.com,Clifford Almanza,Vergie Almanza,Darby,7/1/1958,...,Stet,Carroll,Stet,MO,64680,Midwest,jlalmanza,default,default value,Jenell Almanza
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488800,Mr.,Roberto,R,Harter,M,roberto.harter@exxonmobil.com,Murray Harter,Merideth Harter,Musgrove,7/9/1994,...,New York City,New York,New York City,NY,10185,Northeast,rrharter,default,default value,Roberto Harter
428330,Hon.,Brittni,B,Cyr,F,brittni.cyr@earthlink.net,Williams Cyr,Darleen Cyr,Henderson,3/16/1970,...,Willow Spring,Wake,Willow Spring,NC,27592,South,bbcyr,default,default value,Brittni Cyr
313027,Mr.,Gerald,J,Beaudry,M,gerald.beaudry@shaw.ca,Zachary Beaudry,Sadie Beaudry,Labelle,4/21/1982,...,Burney,Burney,Burney,IN,47222,Midwest,gjbeaudry,default,default value,Gerald Beaudry
826852,Mrs.,Emilee,D,Emery,F,emilee.emery@gmail.com,Andres Emery,Lavina Emery,Metzler,6/18/1967,...,Madison,Dane,Madison,WI,53706,Midwest,edemery,default,default value,Emilee Emery
948300,Ms.,Larhonda,G,Dozier,F,larhonda.dozier@aol.com,Houston Dozier,Gene Dozier,Richard,1/8/1987,...,Spokane,Spokane,Spokane,WA,99224,West,lgdozier,default,default value,Larhonda Dozier

### Removing columns

In [70]:
#df.drop("New col", axis="columns")
df.drop(859327)

,NAME_PREFIX,FIRST_NAME,MIDDLE_INITIAL,LAST_NAME,GENDER,EMAIL_ADDRESS,FATHER'S_NAME,MOTHER'S_NAME,MOTHER'S_MAIDEN_NAME,DATE_OF_BIRTH,...,PLACE_NAME,COUNTY,CITY,STATE,ZIP,REGION,USER_NAME,PASSWORD,New col,Full name
Emp ID,,,,,,,,,,,,,,,,,,,,,
526540,Ms.,Angelique,K,Goodwin,F,angelique.goodwin@gmail.com,Rick Goodwin,Dorian Goodwin,Maxey,5/15/1964,...,Rochester,Monroe,Rochester,NY,14624,Northeast,akgoodwin,default,default value,Angelique Goodwin
887387,Ms.,Donald,T,Farris,F,donald.farris@bellsouth.net,Mauro Farris,Edyth Farris,Greer,4/11/1958,...,Hodges,Franklin,Hodges,AL,35571,South,dtfarris,default,default value,Donald Farris
779497,Hon.,Steven,D,Rendon,M,steven.rendon@gmail.com,Elden Rendon,Angela Rendon,Ortiz,4/4/1982,...,Savoy,Champaign,Savoy,IL,61874,Midwest,sdrendon,default,default value,Steven Rendon
896517,Drs.,Jenell,L,Almanza,F,jenell.almanza@yahoo.com,Clifford Almanza,Vergie Almanza,Darby,7/1/1958,...,Stet,Carroll,Stet,MO,64680,Midwest,jlalmanza,default,default value,Jenell Almanza
220965,Mrs.,Almeta,Y,Brookins,F,almeta.brookins@gmail.com,Richard Brookins,Angelika Brookins,Pape,5/8/1985,...,Lyons,Toombs,Lyons,GA,30436,South,aybrookins,default,default value,Almeta Brookins
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488800,Mr.,Roberto,R,Harter,M,roberto.harter@exxonmobil.com,Murray Harter,Merideth Harter,Musgrove,7/9/1994,...,New York City,New York,New York City,NY,10185,Northeast,rrharter,default,default value,Roberto Harter
428330,Hon.,Brittni,B,Cyr,F,brittni.cyr@earthlink.net,Williams Cyr,Darleen Cyr,Henderson,3/16/1970,...,Willow Spring,Wake,Willow Spring,NC,27592,South,bbcyr,default,default value,Brittni Cyr
313027,Mr.,Gerald,J,Beaudry,M,gerald.beaudry@shaw.ca,Zachary Beaudry,Sadie Beaudry,Labelle,4/21/1982,...,Burney,Burney,Burney,IN,47222,Midwest,gjbeaudry,default,default value,Gerald Beaudry
826852,Mrs.,Emilee,D,Emery,F,emilee.emery@gmail.com,Andres Emery,Lavina Emery,Metzler,6/18/1967,...,Madison,Dane,Madison,WI,53706,Midwest,edemery,default,default value,Emilee Emery
948300,Ms.,Larhonda,G,Dozier,F,larhonda.dozier@aol.com,Houston Dozier,Gene Dozier,Richard,1/8/1987,...,Spokane,Spokane,Spokane,WA,99224,West,lgdozier,default,default value,Larhonda Dozier

### Sorting data

In [73]:
df.sort_values(by="FIRST_NAME", ascending=False)

,NAME_PREFIX,FIRST_NAME,MIDDLE_INITIAL,LAST_NAME,GENDER,EMAIL_ADDRESS,FATHER'S_NAME,MOTHER'S_NAME,MOTHER'S_MAIDEN_NAME,DATE_OF_BIRTH,...,PLACE_NAME,COUNTY,CITY,STATE,ZIP,REGION,USER_NAME,PASSWORD,New col,Full name
Emp ID,,,,,,,,,,,,,,,,,,,,,
455253,Mrs.,Zulma,R,Barnett,F,zulma.barnett@hotmail.com,Broderick Barnett,Shalonda Barnett,Mangum,5/14/1958,...,Koleen,Greene,Koleen,IN,47439,Midwest,zrbarnett,default,default value,Zulma Barnett
772602,Ms.,Zula,X,Romeo,F,zula.romeo@verizon.net,Rudolph Romeo,Oretha Romeo,Prince,1/18/1966,...,Syracuse,Onondaga,Syracuse,NY,13251,Northeast,zxromeo,default,default value,Zula Romeo
150828,Mrs.,Zoraida,V,Sanchez,F,zoraida.sanchez@charter.net,Luther Sanchez,Anisha Sanchez,Bonner,3/29/1968,...,Meridale,Delaware,Meridale,NY,13806,Northeast,zvsanchez,default,default value,Zoraida Sanchez
578209,Mrs.,Zora,N,Maupin,F,zora.maupin@aol.com,Edwardo Maupin,Alda Maupin,Perryman,12/25/1957,...,Ribera,San Miguel,Ribera,NM,87560,West,znmaupin,default,default value,Zora Maupin
763441,Ms.,Zenobia,L,Tejada,F,zenobia.tejada@gmail.com,Gerry Tejada,Ute Tejada,Clevenger,8/12/1960,...,Rosedale,Bolivar,Rosedale,MS,38769,South,zltejada,default,default value,Zenobia Tejada
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397951,Mr.,Abdul,O,Campos,M,abdul.campos@rediffmail.com,Rodger Campos,Pearly Campos,Ammons,7/28/1980,...,Norwalk,Fairfield,Norwalk,CT,6857,Northeast,aocampos,default,default value,Abdul Campos
124463,Hon.,Abdul,H,Jennings,M,abdul.jennings@aol.com,Murray Jennings,Ricki Jennings,Roper,6/25/1959,...,Louisville,Jefferson,Louisville,KY,40253,South,ahjennings,default,default value,Abdul Jennings
299105,Ms.,Abby,V,Gomez,F,abby.gomez@gmail.com,Mario Gomez,Patty Gomez,Spangler,4/21/1981,...,Marietta,Cobb,Marietta,GA,30006,South,avgomez,default,default value,Abby Gomez
423476,Ms.,Abby,I,Chong,F,abby.chong@gmail.com,Javier Chong,Jayne Chong,Muniz,7/31/1987,...,Tulia,Swisher,Tulia,TX,79088,South,aichong,default,default value,Abby Chong
859085,Mr.,Aaron,Y,Laplante,M,aaron.laplante@hotmail.com,Harley Laplante,Tomika Laplante,Medley,3/31/1978,...,Spring Valley,Fillmore,Spring Valley,MN,55975,Midwest,aylaplante,default,default value,Aaron Laplante

### Grouping data

In [78]:
group = df.groupby("REGION")

In [79]:
group.get_group("West")

,NAME_PREFIX,FIRST_NAME,MIDDLE_INITIAL,LAST_NAME,GENDER,EMAIL_ADDRESS,FATHER'S_NAME,MOTHER'S_NAME,MOTHER'S_MAIDEN_NAME,DATE_OF_BIRTH,...,PLACE_NAME,COUNTY,CITY,STATE,ZIP,REGION,USER_NAME,PASSWORD,New col,Full name
Emp ID,,,,,,,,,,,,,,,,,,,,,
495667,Mr.,Cory,H,Clarke,M,cory.clarke@shell.com,Lynwood Clarke,Fallon Clarke,Velez,6/2/1980,...,Mesa,Maricopa,Mesa,AZ,85207,West,chclarke,default,default value,Cory Clarke
489275,Ms.,Collene,O,Kidd,F,collene.kidd@shell.com,Rene Kidd,Lili Kidd,Knight,2/25/1965,...,Reedley,Fresno,Reedley,CA,93654,West,cokidd,default,default value,Collene Kidd
466560,Hon.,Dolores,A,Begley,F,dolores.begley@hotmail.com,Wilmer Begley,Jaqueline Begley,Goldman,12/16/1981,...,Shasta Lake,Shasta,Shasta Lake,CA,96019,West,dabegley,default,default value,Dolores Begley
976422,Mr.,Jake,W,Espinal,M,jake.espinal@shaw.ca,Edmundo Espinal,Charlott Espinal,Duran,1/19/1959,...,Ventura,Ventura,Ventura,CA,93003,West,jwespinal,default,default value,Jake Espinal
713294,Mr.,Sammy,Y,Dewitt,M,sammy.dewitt@ibm.com,Issac Dewitt,Laurene Dewitt,Moniz,1/24/1988,...,Redondo,King,Redondo,WA,98054,West,sydewitt,default,default value,Sammy Dewitt
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
574746,Mr.,Cortez,S,Easter,M,cortez.easter@sbcglobal.net,Josh Easter,Loida Easter,Strong,11/16/1970,...,Biggs,Butte,Biggs,CA,95917,West,cseaster,default,default value,Cortez Easter
692473,Mr.,Hugo,J,Joiner,M,hugo.joiner@ntlworld.com,Lauren Joiner,Lenora Joiner,Lindley,12/7/1972,...,Honolulu,Honolulu,Honolulu,HI,96824,West,hjjoiner,default,default value,Hugo Joiner
699529,Hon.,Spencer,V,Danforth,M,spencer.danforth@gmail.com,Lawerence Danforth,Angila Danforth,Bard,1/20/1984,...,Plummer,Benewah,Plummer,ID,83851,West,svdanforth,default,default value,Spencer Danforth
168076,Mr.,Romeo,Z,Goodwin,M,romeo.goodwin@gmail.com,Marcus Goodwin,Shakia Goodwin,Mcswain,6/14/1975,...,Broomfield,Broomfield,Broomfield,CO,80023,West,rzgoodwin,default,default value,Romeo Goodwin
948300,Ms.,Larhonda,G,Dozier,F,larhonda.dozier@aol.com,Houston Dozier,Gene Dozier,Richard,1/8/1987,...,Spokane,Spokane,Spokane,WA,99224,West,lgdozier,default,default value,Larhonda Dozier

In [84]:
group["STATE"].value_counts()

REGION     STATE
Midwest    IL       189
           OH       167
           MO       141
           IN       129
           MI       127
           MN       127
           WI       124
           IA       122
           KS       100
           NE        77
           SD        48
           ND        46
Northeast  PA       254
           NY       247
           MA        88
           NJ        67
           ME        54
           CT        49
           VT        39
           NH        30
           RI        13
South      TX       331
           FL       161
           VA       153
           KY       142
           NC       130
           WV       128
           GA       125
           AL       109
           OK       105
           LA        89
           TN        84
           MD        74
           MS        74
           AR        71
           SC        58
           DC        31
           DE         5
West       CA       326
           WA       103
           AZ        69
           CO        67
           OR        60
           MT        53
           NM        52
           ID        39
           UT        32
           WY        32
           NV        31
           AK        16
           HI        12
Name: STATE, dtype: int64

### Saving the modified dataset

In [85]:
df.to_csv("employees_modified.csv")